export const MenClothing = [
  {
    id: 1,
    img: "https://tommy-europe.scene7.com/is/image/TommyEurope/KB0KB03973_911_main?$main$",
    price: "$53",
    brand: "Tommy Hilfiger",
    details: "Slim Fit Jeans",
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/31galzBHKVL._SS400_.jpg",
    price: "$150",
    brand: "Clarks",
    details: "Wallabees",
  },
  {
    id: 3,
    img: "https://clarks.scene7.com/is/image/Pangaea2Build/26155527_W_1?fmt=jpg&wid=300",
    price: "$200",
    brand: "Clarks",
    details: "Desert",
  },
  {
    id: 4,
    img: "https://img.cdn.mountainwarehouse.com/product/053054/053054_bla_seasons_ii_padded_jacket_men_aw22_02.jpg",
    price: "$75",
    brand: "Mountain Warehouse",
    details: "Winter Jacket",
  },
  {
    id: 5,
    img: "https://imagescdn.simons.ca/images/9659/22002/10/A1_2.jpg?__=27",
    price: "$35",
    brand: "Polo",
    details: "Hat",
  },
  {
    id: 6,
    img: "https://www.code-zero.com/uploads/media/25/e3/42/1652440866/polo-shirt-yachting.jpg",
    price: "$100",
    brand: "Polo",
    details: "Yacht Racing",
  },
  {
    id: 7,
    img: "https://www.optimized-rlmedia.io/is/image/PoloGSI/s7-1435831_lifestyle?$plpDeskRF$",
    price: "$50",
    brand: "Ralph Lauren",
    details: "Men's Orange Shorts",
  },
  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/61XAFqs-5BL.jpg",
    price: "$35",
    brand: "Ralph Lauren",
    details: "Slides",
  },
  {
    id: 9,
    img: "https://cdna.lystit.com/200/250/tr/photos/lvr/b649ad6b/gucci-Black-4cm-Gg-Supreme-Canvas-Leather-Belt.jpeg",
    price: "$500",
    brand: "Gucci",
    details: "Belt",
  },
  {
    id: 10,
    img: "https://cdn-images.farfetch-contents.com/17/42/95/74/17429574_36141054_300.jpg",
    price: "$300",
    brand: "Gucci",
    details: "Sweatpants",
  },
  {
    id: 11,
    img: "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/080/951/376/original/612582_01.jpg.jpeg?action=crop&width=750",
    price: "$550",
    brand: "Dior Arsham",
    details: "Sweatpants",
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/71GDdpDHvzL.jpg",
    price: "$1000",
    brand: "Louis Vitton",
    details: "Sling Bag",
  },
];
